### ISSUE TITLE
Typescript declaration

### ISSUE THREAD

**Issue by Eun** [rochars/byte-data#1]
Hey It would be super nice if you could add a typescript declaration!

In any case thanks for your work :+1:

**Comment by rochars** [comment]
Could you help me with that?

Cheers! :)

**Comment by Eun** [comment]
Maybe this helps:
https://github.com/DefinitelyTyped/DefinitelyTyped/
https://github.com/Microsoft/dts-gen

**Comment by rochars** [comment]
Included in the roadmap:
https://github.com/rochars/byte-data/blob/master/ROADMAP.md

**Comment by rochars** [comment]
Added in v12.0.1
